### PR TITLE
feat: show LP tokens in add form details

### PR DESCRIPTION
**Pull request by agualis**
LPtokens

Example use case: 
Trying to see how much veBAL I would get depositing vs. swapping.

### CODE REVIEW

**Review by uiuxxx — APPROVED** [review]
Looks good to me

**Review by garethfuller — COMMENTED** [review]
Can you think of any cases where this might cause problems? e.g. if approvals have not been done? Is there not a case where simulations fail until approvals are in place?

**Comment by agualis** [comment]
> Can you think of any cases where this might cause problems? e.g. if approvals have not been done? Is there not a case where simulations fail until approvals are in place?

Good point. I don't think we have that problem in add simulations.

However, I realised that pools requiring proportional inputs are not showing this LP tokens field as these pools do not display price impact details:

Screenshot 2024-10-09 at 12 40 33

**Comment by garethfuller** [comment]
@agualis I think it's fine to leave this as it is for now. If this feature is needed on CoW pools we can do that in another PR when requested.

**Review by garethfuller — APPROVED** [review]

**Pull request merged**
