### PR TITLE
feat: enable fx pools

### PR DESCRIPTION
**Pull request by 0xnook**
* displays Xave's fxpools on pool list
* displays fx pool data and stats
* links to Xave's interface to add/remove liquidity

Some data is still not correctly displayed, like the pool swap fee apr, pool owner, and pool attribute immutability. Using the swap interface also does not route through these pools.

However, these inaccuracies where also present in the frontend-v2 UI.

### CODE REVIEW

**Comment by 0xnook** [comment]
resolves #973

**Comment by garethfuller** [comment]
@0xnook what's the state here? Would be great to get this working. When I first checked I think something was required on the API side first?

**Comment by andreiashu** [comment]
hi @0xnook @garethfuller Xave team member here. If there's anything we can help with let me know.
Thanks for opening this PR!

**Review by garethfuller — CHANGES_REQUESTED** [review]
Could you add a label for the filter here? https://github.com/balancer/frontend-v3/blob/main/lib/modules/pool/PoolList/usePoolListQueryState.tsx#L113-L128 I think it should be `FX` instead of `Fx` right?

**Comment by 0xnook** [comment]
> I think it should be `FX` instead of `Fx` right?

I think so. Added the label

**Review by garethfuller — APPROVED** [review]

**Pull request merged**
