### PR TITLE
chore: windows dev support

### PR DESCRIPTION
**Pull request by crutch12**
Since Windows doesn't support providing env variables using command line - we should use `cross-env` package

### CODE REVIEW

**Review by garethfuller — COMMENTED** [review]
Hey! Thanks for contributing. It seems this change causes the build check to fail.

**Comment by crutch12** [comment]
> Hey! Thanks for contributing. It seems this change causes the build check to fail.

Hi!

Error message from workflow https://github.com/balancer/frontend-v3/actions/runs/10524841452/job/29166397708?pr=993
> Error: No projectId found. Every dApp must now provide a WalletConnect Cloud projectId to enable WalletConnect v2 https://www.rainbowkit.com/docs/installation#configure

`pnpm build` locally works fine

Moreover, event tiny PRs (e.g. https://github.com/balancer/frontend-v3/pull/992) have the same checks errors. Thus my changes are not the reason of fail...

**Comment by garethfuller** [comment]
Thanks, yeah just realised that. Something must have changed. Looking into it.

**Review by garethfuller — APPROVED** [review]
Seems to be an issue with being an external contributor. I set up the same PR here #996 and the build passes.

**Pull request merged**
